work_dir: work_dir/Debug/singlegpu/1gpu_bz128_pergpu/seed2/Base/spatial_shear_tem_padding/queue_32768/Tem_0.2/with_MLP/skeclr_multi_swap/semantic_swap/64_1_48_1_32_1_16_1/st_gcn/agcn_graph/ntu/joint/semi_0.1_evaluation_0_xview_frame64_channel16_feature128_hidden256_epoch300_model300
weights:  work_dir/Debug/singlegpu/1gpu_bz128_pergpu/seed2/Base/spatial_shear_tem_padding/queue_32768/Tem_0.2/with_MLP/skeclr_multi_swap/semantic_swap/64_1_48_1_32_1_16_1/st_gcn/agcn_graph/ntu/joint/0_xview_frame64_channel16_feature128_hidden256_epoch300/epoch300_model.pt

ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_semi
train_feeder_args:
  data_path: data/Base/NTU60_frame64/xview/train_position.npy
  label_path: data/Base/NTU-RGB-D/xview/train_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  center: True
  mmap: True
  label_percent: 0.1
  
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: data/Base/NTU60_frame64/xview/val_position.npy
  label_path: data/Base/NTU-RGB-D/xview/val_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  center: True
  mmap: True

# model
model: net.skeletonclr.SkeletonCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
#  margin: 0.7
#  topN: 32
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.01
optimizer: SGD
step: []
warm_up_epoch: 0

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 200
view: 'joint'

# log
save_interval: -1
eval_interval: 5
knn_interval: -1
